Synchronize changes from alt-1
SKA-ScienceDataProcessor/alaska-kayobe-config pull request #88
Opened 2018-08-24 15:30 UTC by jovial

This is an attempt to bring in all changes that have been applied to alt-1 but not yet made it to p3.

2018-08-24 16:25 UTC, markgoddard requested changes
Nick hasn't deployed the Keystone federation changes in production yet, so we'll need to revert those.

2018-08-24 16:25 UTC, markgoddard commented on etc/kayobe/kolla.yml
> +      - controllers
I think we need to stick with the default here. Monitoring runs on the controller in alt-1, but has its own node in production

2018-08-24 16:25 UTC, markgoddard commented on etc/kayobe/overcloud.yml
> +disable_cloud_init: True
We've got these lines twice now

2018-08-24 16:25 UTC, markgoddard commented on etc/kayobe/kolla/passwords.yml
>  $ANSIBLE_VAULT;1.1;AES256
Checked the diff and there are no changes in the decrypted file

2018-08-28 14:10 UTC, jovial commented
Couldn't find a cleaner way than reverting the keystone commit

2018-08-28 14:44 UTC, markgoddard approved these changes

2018-08-28 14:45 UTC, markgoddard commented on etc/kayobe/secrets.yml
> -64353261323166643863303933386131666130623233303335363830383962383134393537313262
Despite the changes, this is a noop. Not worth worrying about.

2018-08-28 14:45 UTC, markgoddard commented on etc/kayobe/kolla.yml
> +kolla_enable_ironic_ipxe: True
We'd need to redeploy ironic to enable ipxe.

2018-08-28 15:43 UTC, merged