Workaround for IPA DIB failing with pip > 10
SKA-ScienceDataProcessor/alaska-kayobe-config pull request #93
Opened 2018-08-29 13:18 UTC by jovial

Symptom:

```
TASK [stackhpc.os-images : Fail if any images failed to build] **********************
failed: [sv-b16-u23] (item=[{u'elements': [u'centos7', u'enable-serial-console', u'ironic-agent', u'ipa-extra-hardware', u'mellanox', u'stackhpc-ipa-hardware-managers'], u'type': u'raw', u'name': u'ipa', u'env': {u'DIB_REPOREF': u'refs/tags/stackhpc/2.2.3.1', u'DIB_REPOLOCATION': u'https://github.com/stackhpc/ironic-python-agent'}}, 1]) => {"failed": true, "item": [{"elements": ["centos7", "enable-serial-console", "ironic-agent", "ipa-extra-hardware", "mellanox", "stackhpc-ipa-hardware-managers"], "env": {"DIB_REPOLOCATION": "https://github.com/stackhpc/ironic-python-agent", "DIB_REPOREF": "refs/tags/stackhpc/2.2.3.1"}, "name": "ipa", "type": "raw"}, 1], "msg": "Image ipa failed to build. See ipa.stdout and ipa.stderr in /opt/kayobe/images/ipa.\n"}
```

2018-08-29 13:23 UTC, markgoddard requested changes

2018-08-29 13:23 UTC, markgoddard commented on etc/kayobe/ipa.yml
> +ipa_build_dib_env_default:
I think we need to use ipa_build_dib_env_extra here to ensure this env var is added to the defaults.

2018-08-29 17:56 UTC, markgoddard approved these changes

2018-08-29 17:57 UTC, merged

2018-09-03 21:50 UTC, brtknr commented on etc/kayobe/ipa.yml
> +  DIB_INSTALLTYPE_pip_and_virtualenv: package
wow, the mix of caps and lower case for the same variable is slightly startling.